name: 'Application'
variables:
  BuildConfiguration: 'Release'
  BuildPlatform: 'any cpu'
  CI: true
trigger: [ 'master' ]
jobs:
  - job: 'Backend'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: 'DotNetCoreCLI@2'
        displayName: 'Restore'
        inputs:
          command: 'restore'
          projects: '**/GovUk.*/*csproj'
      - task: 'DotNetCoreCLI@2'
        displayName: 'Build'
        inputs:
          projects: '**/GovUk.*/*csproj'
          arguments: '--configuration $(BuildConfiguration)'

      #  - task: DotNetCoreCLI@2
      #    displayName: Build
      #    inputs:
      #      projects: '$(Parameters.RestoreBuildProjects)'
      #      arguments: '--configuration $(BuildConfiguration)'
      #
      #  - task: DotNetCoreCLI@2
      #    displayName: Test
      #    inputs:
      #      command: test
      #      projects: '$(Parameters.TestProjects)'
      #      arguments: '--configuration $(BuildConfiguration)'
      #
      #  - task: DotNetCoreCLI@2
      #    displayName: Publish
      #    inputs:
      #      command: publish
      #      publishWebProjects: false
      #      projects: '$(Parameters.RestoreBuildProjects)'
      #      arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
      #      zipAfterPublish: True
      #
      #  - task: CopyFiles@2
      #    displayName: 'Copy ARM templates'
      #    inputs:
      #      SourceFolder: armTemplates
      #      TargetFolder: '$(Build.ArtifactStagingDirectory)'

      #  - task: PublishPipelineArtifact@0
      #    displayName: 'Publish Pipeline Artifact'
      #    inputs:
      #      artifactName: backend
      #      targetPath: '$(Build.ArtifactStagingDirectory)'
      #
      #  - job: 'Frontend_Test'
      #    steps:
      #      - script: echo Frontend Test step!
      #  - job: 'Frontend_Build_Test'
      #    dependsOn: 'Frontend_Test'
      #    steps:
      #      - script: echo Frontend Build Test step!
      #  - job: 'Frontend_Build_Stage'
      #    dependsOn: 'Frontend_Test'
      #    steps:
      #      - script: echo Frontend Build Stage step!
      #  - job: 'Frontend_Build_Live'
      #    dependsOn: 'Frontend_Test'
      #    steps:
      #      - script: echo Frontend Build Live step!
