jobs:
  - job: 'Backend'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: echo Backend step!
  - job: 'Frontend_Test'
    steps:
      - script: echo Frontend Test step!
  - job: 'Frontend_Build_Test'
    dependsOn: 'Frontend_Test'
    steps:
      - script: echo Frontend Build Test step!
  - job: 'Frontend_Build_Stage'
    dependsOn: 'Frontend_Test'
    steps:
      - script: echo Frontend Build Stage step!
  - job: 'Frontend_Build_Live'
    dependsOn: 'Frontend_Test'
    steps:
      - script: echo Frontend Build Live step!
